### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by zinoff** [moritzdietz/pi-syncscript#8]
Thank you for putting this script together it's great, the repo I was using before had a very old version. 
This is **not** really an issue, but the standard configuration you ship does not really work for me (I need to change the ports). 
How do I go about changing the configuration?

**Comment by moritzdietz** [comment]
Just as a clarification for people reading this also: The configuration I am hosting here on this repository is straight from the package BitTorrent Inc. provides for the Raspberry Pi.

So about your issue with the configuration file you should do the following.
- sudo killall btsync
- nano /etc/btsync/config.json
- Do your changes to the file and save it
- Restart BitTorrent Sync again with "sudo service btsync start"

A general FYI about ports: Binding ports 1-1024 require root ([Link](https://forums.freenas.org/index.php?threads/btsync-using-port-80-for-gui.22453/))

You can also always check your configuration the following way:
Run `/usr/bin/btsync --nodaemon --config /etc/btsync/config.json` and see what you get as output.
From there you will see errors in your configuration or in general really easy.

Did that help? If yes, let me please know so I can close this issue.

**Comment by zinoff** [comment]
Great, thank you. Issue closed.
