### ISSUE TITLE
Failed to start btsync.service: Unit btsync.service failed to load: No such file or directory.

### ISSUE THREAD

**Issue by zgdk** [moritzdietz/pi-syncscript#9]
The mentioned error message keep popping upon on a completely fresh install of Raspbian Jessie. I suspect the problem is in the switch to systemd as the mentioned btsync.service is a systemd file. However setting it to run at startup works correctly.

**Comment by moritzdietz** [comment]
Yeah I haven't done anything towards systemd.. although this will resolve itself in a week or so (you'll see when it happens)
I will keep this issue updated. So as of now: there are some issues with Raspbian Jessie.

I myself don't have a jessie installation; will check it out over the weekend tho.

**Comment by moritzdietz** [comment]
Sorry not going to happen this weekend. I will look into it over the upcoming week.

**Comment by moritzdietz** [comment]
I am wondering now.. how are you starting BitTorrent Sync?

**Comment by moritzdietz** [comment]
Ok so I can confirm that using this script it doesn't work on Raspbian Jessie.

What I would suggest is you using the official repository for now - guessing you haven't used my script on your Raspberry Pi before and don't have current sync data on it.
I will update my readme to reflect that right now this script doesn't support Jessie.
